server:
  port: 8761
spring:
  application:
    name: registry
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  server:
      # 关闭自我保护模式（默认为打开）
      enable-self-preservation: false
      # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
      eviction-interval-timer-in-ms: 50000